
patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 633834615594.dkr.ecr.us-west-2.amazonaws.com/samplewebapp
  newName: 633834615594.dkr.ecr.us-west-2.amazonaws.com/samplewebapp
  newTag: a408c07ed70099a809ed9cc61b3b4aec1d8a278a
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
